
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 05 11:30:09 CST 2017
//----------------------------------------------------

package P1_C1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int close_par = 5;
  public static final int or_ = 14;
  public static final int elsee = 23;
  public static final int igual_igual = 16;
  public static final int main = 20;
  public static final int pyc_ = 12;
  public static final int and_ = 15;
  public static final int putw = 25;
  public static final int multiplicacion = 8;
  public static final int whilee = 22;
  public static final int no_igual = 17;
  public static final int resta = 7;
  public static final int puts = 24;
  public static final int intt = 26;
  public static final int menor = 19;
  public static final int open_lla = 2;
  public static final int EOF = 0;
  public static final int division = 9;
  public static final int id = 10;
  public static final int iff = 21;
  public static final int open_par = 4;
  public static final int error = 1;
  public static final int entero = 11;
  public static final int suma = 6;
  public static final int close_lla = 3;
  public static final int mayor = 18;
  public static final int asignacion_ = 13;
}

