
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jun 04 09:30:30 CST 2017
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 24;
  public static final int ASIGNADOR = 4;
  public static final int INT = 12;
  public static final int WHILE = 25;
  public static final int SUMA = 5;
  public static final int DIVI = 8;
  public static final int MULTI = 7;
  public static final int OROR = 18;
  public static final int IF = 23;
  public static final int EQUEQU = 22;
  public static final int PARENT_CE = 15;
  public static final int MAYOR = 20;
  public static final int EOF = 0;
  public static final int LLAB_CE = 17;
  public static final int DIFERENTE = 13;
  public static final int MAIN = 26;
  public static final int ANDAND = 19;
  public static final int MINOR = 21;
  public static final int PUTW = 11;
  public static final int error = 1;
  public static final int NUMERO = 2;
  public static final int IDENTIFICADOR = 3;
  public static final int PUTS = 10;
  public static final int PUNTO_COMA = 9;
  public static final int PARENT_AB = 14;
  public static final int LLAB_AB = 16;
  public static final int RESTA = 6;
}

